spring.application.name=Immigration_Management_System_Demo
spring.datasource.url=jdbc:mysql://localhost:3306/immigrationdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=MySQL@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true